#include "T7RunnerEnginePluginPCH.h"

#ifndef VBASE_LIB

#include <Common/Base/keycode.cxx>

#define HK_EXCLUDE_FEATURE_SerializeDeprecatedPre700

#undef HAVOK_ANIMATION_KEYCODE
#undef HK_FEATURE_PRODUCT_ANIMATION
#undef HAVOK_BEHAVIOR_KEYCODE
#undef HK_FEATURE_PRODUCT_BEHAVIOR
#undef HAVOK_CLOTH_KEYCODE
#undef HK_FEATURE_PRODUCT_CLOTH
#undef HAVOK_DESTRUCTION_2012_KEYCODE
#undef HK_FEATURE_PRODUCT_DESTRUCTION_2012
#undef HAVOK_DESTRUCTION_KEYCODE
#undef HK_FEATURE_PRODUCT_DESTRUCTION
#undef HAVOK_AI_KEYCODE 
#undef HK_FEATURE_PRODUCT_AI
#undef HAVOK_SIMULATION_KEYCODE 
#undef HK_FEATURE_PRODUCT_SIMULATION
#undef HAVOK_PHYSICS_KEYCODE 
#undef HK_FEATURE_PRODUCT_PHYSICS

#include <Common/Base/hkBase.h>
#include <Common/Base/Config/hkProductFeatures.cxx>

#endif
